import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Provider } from 'react-redux';
import { store } from '@/provider/store/store';
import ReduxWrapper from '@/provider/store/ReduxWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ReduxWrapper>
			<html lang='en'>
				<body className={inter.className}>{children}</body>
			</html>
		</ReduxWrapper>
	);
}
